<?php
    use EmbyPlaylistApp\PlaylistFile;
?>
<div>
    <a class="back" href="<?php echo $homeUrl; ?>/playlists">back...</a>
</div>

<h1>Edit Playlist</h1>

<?php if(isset($message) && $message):?>
<div class="message">
    <?php echo $message; ?>
</div>
<?php endif; ?>

<form method="POST" action="<?php echo $homeUrl; ?>/api/playlists" class="playlist-editor">
    <div>
        <input type="submit" value="<?php echo strlen($playlistName) ? 'Save' : 'Create'; ?>" class="high-emphasis"/>
        <a href="<?php echo $homeUrl; ?>/playlists/edit?name=<?php echo $playlistName; ?>" class="button mid-emphasis">Cancel</a>
    </div>

    <div>
        <label>Name <input type="text" name="name" value="<?php echo $playlistName; ?>" /></label>
        <input type="hidden" name="original_name" value="<?php echo $playlistName; ?>" />
    </div>
    <?php if(count($files)): ?>
        <h2>Songs</h2>
        <ul class="playlist filelist">
            <?php $count = 0; foreach($files as $file): ?>
            <li class="playlist-item item<?php echo $count; ?>" data-count="<?php echo $count; ?>"><label><?php 
                echo str_replace($location, '', $file); 
            ?><input type="hidden" name="files[]" value="<?php echo $file; ?>" /></label></li>
            <?php $count++; endforeach; ?>
        </ul>
    <?php endif; ?>

    <div>
        <input type="submit" value="<?php echo strlen($playlistName) ? 'Save' : 'Create'; ?>" class="high-emphasis"/>
        <a href="<?php echo $homeUrl; ?>/playlists/edit?name=<?php echo $playlistName; ?>" class="button mid-emphasis">Cancel</a>
    </div>
</form>