<?php
    use EmbyPlaylistApp\PlaylistFile;

    $appTitle = "Emby Playlist App";
    $description = "An app to help create playlists for Emby servers";
    $title = isset($title) ? $title . ' | ' . $appTitle : $appTitle;
    $homeUrl = getenv('APPLICATION_ROOT_URL');

    $location = getenv('PLAYLISTS');
    $listNames = PlaylistFile::getPlaylistNames($location);


    $template = 'home';
    switch(isset($page) ? $page : false) {
        case 'files': $template = 'files';break;
        case 'playlists': $template = 'playlists';break;
        case 'playlistEditor': $template = 'playlist_edit';break;
        case 'error': $template = '404';break;
        default:;
    }
?><!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title><?php echo $title; ?></title>
        <meta name="description" content="<?php echo $description; ?>">
        <meta name="author" content="<?php echo $appTitle; ?>">
        
        <!-- Open Graph -->
        <meta property="og:site_name" content="<?php echo $title; ?>"/>
        <meta property="og:type" content="website"/>
        <meta property="og:title" content="<?php echo $title; ?>"/>
        <meta property="og:description" content="<?php echo $description; ?>"/>
        <meta property="og:locale" content="en-GB"/>
        <meta property="og:url" content="<?php echo $homeUrl; ?>"/>
        <meta property="og:image" content="<?php echo $homeUrl; ?>/images/library.png"/>
        <meta property="og:image:secure_url" content="<?php echo $homeUrl; ?>/images/library.png"/>
        
        <!-- Twitter Card -->
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:description" content="<?php echo $description; ?>" />
        <meta name="twitter:title" content="<?php echo $homeUrl; ?>" />
        <meta name="twitter:site" content="@embyapp" />
        <meta name="twitter:image" content="<?php echo $homeUrl; ?>/images/library.png" />
        <meta name="twitter:creator" content="@dmcblue" />
        
        <!-- Google JSON-LD -->
        <script type='application/ld+json'><?php echo json_encode([
            '@context' =>  'http://schema.org',
            '@type' => 'WebSite',
            '@id' => '#website',
            'url' => $homeUrl,
            'name' =>  $appTitle,
        ]); ?></script>
        
        <!--<link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>-->
        <link href='<?php echo $homeUrl; ?>/style/emby-playlist-app.css' rel='stylesheet' type='text/css'>
        <script type='application/javascript' src="<?php echo $homeUrl; ?>/js/keys.js"></script>
    </head>
    <body>
        <header>
            <div>
                <nav>
                    <ul>
        <li><a href="<?php echo $homeUrl; ?>" <?php if($template == 'home'): ?>class="active"<?php endif; ?>>Home</a></li>
                        <li><a href="<?php echo $homeUrl; ?>/playlists" <?php if($template == 'playlists'): ?>class="active"<?php endif; ?>>Playlists</a></li>
                        <li><a href="<?php echo $homeUrl; ?>/library" <?php if($template == 'files'): ?>class="active"<?php endif; ?>>Library</a></li>
                    </ul>
                </nav>
            </div>
        </header>

        <div id="content">
            <div>
                <?php 
                    require(implode(DIRECTORY_SEPARATOR, [__DIR__, 'pages', "{$template}.phtml"]));
                ?>
            </div>
        </div>

        <footer>
            <div>
                Emby Playlist App | <a href="https://github.com/dmcblue/emby-playlist-app" target="_blank">(source code)</a> by <a href="http://www.dmcblue.com" target="_blank">dmcblue</a>
            </div>
        </footer>

        <?php
            $path = implode(DIRECTORY_SEPARATOR, [__DIR__, 'menus', "{$template}.phtml"]);
            if(file_exists(__DIR__ . DIRECTORY_SEPARATOR . "menus/{$template}.phtml")) {
                require("menus/{$template}.phtml");
            }
        ?>

        <div id="message-box"></div>

        <input type="hidden" id="baseUrl" value="<?php echo $homeUrl; ?>" />
        <script type='application/javascript' src="<?php echo $homeUrl; ?>/js/emby-playlist-app.js"></script>
    </body>
</html>
